spring:
    profiles:
        active:
            -dev
---
spring: 
    profiles: dev
    application:
        name: serverforDEV1

---
spring:
    profiles: test
    application:
        name: serverforTEST1