spring:
  profiles:
    active:
      - dev
---
server:
  port: 8002

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: salary-8002

spring:
  profiles: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/salary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: SalaryServer-login
  redis:
    host: 47.102.216.221

info:
  aucrot: Hddd
  time: 2020.2.21
mybatis:
  config-location: classpath:mybatis/MybatisConfig.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

---