---
server:
    port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: salary-config-8003

spring:
  application:
    name: SalaryServer-3
  profiles: dev

info:
  aucrot: Hddd
  time: 2020.2.22
 
---

server:
    port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: salary-config-8003-test

spring:
  application:
    name: SalaryServer-3-test
  profiles: test

info:
  aucrot: Hddd
  time: 2020.2.22