spring: 
  profiles: 
    active: 
     - dev

---
server: 
  port: 8003

spring: 
  profiles: dev
  application: 
    name: salary-server-3-dev

info: 
 profile: dev
 auctor: hddd
 time: 2019-8-22

eureka: 
  instance: 
    prefer-ip-address: true
    instance-id: salary-server-8003
  client: 
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/

---
server: 
  port: 8003

spring: 
  profiles: test
  application: 
    name: salary-server-3-test

eureka: 
  instance:
    prefer-ip-address: true
    instance-id: salary-server-8003
  client: 
    service-url: 
     defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
info: 
 profile: test
 auctor: hddd
 time: 2019-8-22
