
spring:
    profiles:
        active:
            -dev

---
server:
    port: 8003
    
spring:
  application:
    name: SalaryServer-3
  profiles: dev
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: salary-config-8003


 
---

server:
    port: 8003
    
spring:
  application:
    name: SalaryServer-3-test
  profiles: test
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: salary-config-8003-test



