spring:
    profiles:
        active:
            -dev
---
server:
    port: 8002

spring:
    profiles: dev
    application:
        name: salary-login-server
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/salary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
        host: 47.102.216.221        
mybatis:
    config-location: classpath:mybatis/MybatisConfig.xml
    mapper-locations: classpath:mybatis/mapper/*.xml

eureka:
    instance:
        prefer-ip-address: true
        instance-id: salary-8002
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/
info:
    name: hddd
    type: dev
---
server:
    port: 8002

spring:
    profiles: test
    application:
        name: salary-login-server

eureka:
    instance:
        prefer-ip-address: true
        instance-id: salary-8002
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/,http://eureka7001.com:7001/eureka/

info:
    name: hddd
    type: test
